version: '3'


#networks:
#  default:
#    external:
#      name: traefik
networks:  
  proxy:
    external:
      name: traefik_proxy


services:


#
# DLUBM_GRANULARITY = GLOBAL
#


# Different templates caused by
#       DLUBM_UNIVERSITY_AMOUNT = 1
#       DLUBM_UNIVERSITY_AMOUNT > 1
# Now
#       DLUBM_UNIVERSITY_AMOUNT = 1

# DLUBM_SEED=0
# DLUBM_GRANULARITY=GLOBAL
# DLUBM_UNIVERSITY_AMOUNT=1
# DLUBM_UNIVERSITY_OFFSET=0
# DLUBM_UNIVERSITY_LIMIT=0
# DLUBM_DEPARTMENT_LIMIT=0
  g_dl0_ul0_uo0_ua1_gg_s0:
#    container_name: "g.dl0.ul0.uo0.ua1.gg.s0.dlubm"
    image: "fekepp/dlubm:1.9.0-pr"
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:g.dl0.ul0.uo0.ua1.gg.s0.dlubm.ddns.me"
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:g.dl0.ul0.uo0.ua1.gg.s0.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dl1.ul1.uo0.ua5.gd.s0.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=GLOBAL
      - DLUBM_UNIVERSITY_AMOUNT=1
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=0
      - DLUBM_UNIVERSITY_TEMPLATE=http://g.dl0.ul0.uo0.ua1.gg.s0.dlubm.ddns.me/#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://g.dl0.ul0.uo0.ua1.gg.s0.dlubm.ddns.me/d{DEPARTMENT_INDEX}/#
      - DLUBM_HOST_DEPTH=GLOBAL
      - DLUBM_HOST_UNIVERSITY_AMOUNT=1
      - DLUBM_HOST_UNIVERSITY_OFFSET=0
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0
    ports:
      - 10000:80


# Different templates caused by
#       DLUBM_UNIVERSITY_AMOUNT = 1
#       DLUBM_UNIVERSITY_AMOUNT > 1
# Now
#       DLUBM_UNIVERSITY_AMOUNT = 2

# DLUBM_SEED=0
# DLUBM_GRANULARITY=GLOBAL
# DLUBM_UNIVERSITY_AMOUNT=2
# DLUBM_UNIVERSITY_OFFSET=0
# DLUBM_UNIVERSITY_LIMIT=0
# DLUBM_DEPARTMENT_LIMIT=0
  g_dl0_ul0_uo0_ua2_gg_s0:
#    container_name: 'g.dl0.ul0.uo0.ua2.gg.s0.dlubm'
    image: 'fekepp/dlubm:1.9.0-pr'
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:g.dl0.ul0.uo0.ua2.gg.s0.dlubm.ddns.me"
#      mode: replicated
#      replicas: 10
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:g.dl0.ul0.uo0.ua2.gg.s0.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dl1.ul1.uo0.ua5.gd.s0.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=GLOBAL
      - DLUBM_UNIVERSITY_AMOUNT=2
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=0
      - DLUBM_UNIVERSITY_TEMPLATE=http://g.dl0.ul0.uo0.ua2.gg.s0.dlubm.ddns.me/u{UNIVERSITY_INDEX}/#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://g.dl0.ul0.uo0.ua2.gg.s0.dlubm.ddns.me/u{UNIVERSITY_INDEX}/d{DEPARTMENT_INDEX}/#
      - DLUBM_HOST_DEPTH=GLOBAL
      - DLUBM_HOST_UNIVERSITY_AMOUNT=2
      - DLUBM_HOST_UNIVERSITY_OFFSET=0
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0
    ports:
      - 10001:80



