version: '3'


networks:
  proxy:
    external:
      name: traefik_proxy


services:




# Different templates caused by
#       DLUBM_UNIVERSITY_LIMIT < 1 (not set)
#       DLUBM_UNIVERSITY_LIMIT = 1
#       DLUBM_UNIVERSITY_LIMIT > 1
#       DLUBM_DEPARTMENT_LIMIT < 1 (not set)
#       DLUBM_DEPARTMENT_LIMIT = 1
#       DLUBM_DEPARTMENT_LIMIT > 1
# Now
#       DLUBM_UNIVERSITY_LIMIT = 1
#       DLUBM_DEPARTMENT_LIMIT = 1

# DLUBM_SEED=0
# DLUBM_GRANULARITY=DEPARTMENT
# DLUBM_UNIVERSITY_AMOUNT=5
# DLUBM_UNIVERSITY_OFFSET=0
# DLUBM_UNIVERSITY_LIMIT=1
# DLUBM_DEPARTMENT_LIMIT=0




##
## ONTOLOGY
##
  s0_gd_ua5_uo0_ul1_dl1_o:
    image: "fekepp/dlubm:1.9.0-pr"
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:o.dlubm.ddns.me"
      replicas: 1
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:o.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=ONTOLOGY
      - DLUBM_UNIVERSITY_AMOUNT=0
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=0
      - DLUBM_UNIVERSITY_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/u#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/d{DEPARTMENT_INDEX}#
      - DLUBM_HOST_DEPTH=GLOBAL
      - DLUBM_HOST_UNIVERSITY_AMOUNT=0
      - DLUBM_HOST_UNIVERSITY_OFFSET=0
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0




##
## GLOBAL
##
  s0_gd_ua5_uo0_ul1_dl1_g:
    image: "fekepp/dlubm:1.9.0-pr"
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:g.dlubm.ddns.me,dlubm.ddns.me"
      replicas: 1
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:g.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=UNIVERSITY
      - DLUBM_UNIVERSITY_AMOUNT=5
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=1
      - DLUBM_UNIVERSITY_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/u#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/d{DEPARTMENT_INDEX}#
      - DLUBM_HOST_DEPTH=GLOBAL
      - DLUBM_HOST_UNIVERSITY_AMOUNT=5
      - DLUBM_HOST_UNIVERSITY_OFFSET=0
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0




##
## UNIVERSITY
##
  s0_gd_ua5_uo0_ul1_dl1_u0:
#    image: "fekepp/dlubm:1.9.0-pr"
    image: "fekepp/dlubm-scal:latest"
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:u0.dlubm.ddns.me"

      replicas: 1
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:u0.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=UNIVERSITY
      - DLUBM_UNIVERSITY_AMOUNT=5
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=1
      - DLUBM_UNIVERSITY_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/u#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/d{DEPARTMENT_INDEX}#
      - DLUBM_HOST_DEPTH=UNIVERSITY
      - DLUBM_HOST_UNIVERSITY_AMOUNT=1
      - DLUBM_HOST_UNIVERSITY_OFFSET=0
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0


  s0_gd_ua5_uo0_ul1_dl1_u1:
#    image: "fekepp/dlubm:1.9.0-pr"
    image: "fekepp/dlubm-scal:latest"
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:u1.dlubm.ddns.me"
      replicas: 1
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:u1.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=UNIVERSITY
      - DLUBM_UNIVERSITY_AMOUNT=5
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=1
      - DLUBM_UNIVERSITY_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/u#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/d{DEPARTMENT_INDEX}#
      - DLUBM_HOST_DEPTH=UNIVERSITY
      - DLUBM_HOST_UNIVERSITY_AMOUNT=1
      - DLUBM_HOST_UNIVERSITY_OFFSET=1
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0


  s0_gd_ua5_uo0_ul1_dl1_u2:
#    image: "fekepp/dlubm:1.9.0-pr"
    image: "fekepp/dlubm-scal:latest"
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:u2.dlubm.ddns.me"
      replicas: 1
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:u2.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=UNIVERSITY
      - DLUBM_UNIVERSITY_AMOUNT=5
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=1
      - DLUBM_UNIVERSITY_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/u#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/d{DEPARTMENT_INDEX}#
      - DLUBM_HOST_DEPTH=UNIVERSITY
      - DLUBM_HOST_UNIVERSITY_AMOUNT=1
      - DLUBM_HOST_UNIVERSITY_OFFSET=2
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0


  s0_gd_ua5_uo0_ul1_dl1_u3:
#    image: "fekepp/dlubm:1.9.0-pr"
    image: "fekepp/dlubm-scal:latest"
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:u3.dlubm.ddns.me"
      replicas: 1
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:u3.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=UNIVERSITY
      - DLUBM_UNIVERSITY_AMOUNT=5
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=1
      - DLUBM_UNIVERSITY_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/u#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/d{DEPARTMENT_INDEX}#
      - DLUBM_HOST_DEPTH=UNIVERSITY
      - DLUBM_HOST_UNIVERSITY_AMOUNT=1
      - DLUBM_HOST_UNIVERSITY_OFFSET=3
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0


  s0_gd_ua5_uo0_ul1_dl1_u4:
#    image: "fekepp/dlubm:1.9.0-pr"
    image: "fekepp/dlubm-scal:latest"
    deploy:
      labels:
        - "traefik.docker.network=traefik_proxy"
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:u4.dlubm.ddns.me"
      replicas: 1
    labels:
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:u4.dlubm.local"
    networks:
      - proxy
    environment:
      - DLUBM_ONTOLOGY=http://o.dlubm.ddns.me/univ-bench.owl
      - DLUBM_SEED=0
      - DLUBM_GRANULARITY=UNIVERSITY
      - DLUBM_UNIVERSITY_AMOUNT=5
      - DLUBM_UNIVERSITY_OFFSET=0
      - DLUBM_UNIVERSITY_LIMIT=1
      - DLUBM_UNIVERSITY_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/u#
      - DLUBM_DEPARTMENT_LIMIT=0
      - DLUBM_DEPARTMENT_TEMPLATE=http://u{UNIVERSITY_INDEX}.dlubm.ddns.me/d{DEPARTMENT_INDEX}#
      - DLUBM_HOST_DEPTH=UNIVERSITY
      - DLUBM_HOST_UNIVERSITY_AMOUNT=1
      - DLUBM_HOST_UNIVERSITY_OFFSET=4
      - DLUBM_HOST_DEPARTMENT_AMOUNT=0
      - DLUBM_HOST_DEPARTMENT_OFFSET=0

